"""baseline schema from models

Revision ID: 12f9e83a2cfd
Revises: 
Create Date: 2026-05-28 23:25:39.985314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f9e83a2cfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('county_name', sa.String(length=100), nullable=False),
    sa.Column('fips_code', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('annual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_daily_leads', sa.Integer(), nullable=True),
    sa.Column('grid_priority_boost', sa.Integer(), nullable=False),
    sa.Column('analytics_access_level', sa.String(length=20), nullable=True),
    sa.Column('video_recording_enabled', sa.Boolean(), nullable=False),
    sa.Column('custom_branding_enabled', sa.Boolean(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('stripe_price_id_monthly', sa.String(length=100), nullable=True),
    sa.Column('stripe_price_id_annual', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('BORROWER', 'LOAN_OFFICER', 'REALTOR', 'TITLE_REP', 'ATTORNEY', name='usertype'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('device_tokens', sa.JSON(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_platform', sa.String(length=20), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGE', 'ACCOUNT_CREATED', 'ACCOUNT_DISABLED', 'ACCOUNT_ENABLED', 'PROFILE_UPDATED', 'ADMIN_USER_STATUS_CHANGE', 'ADMIN_VIDEO_APPROVED', 'ADMIN_VIDEO_REJECTED', 'ADMIN_DISPUTE_RESOLVED', 'SUBSCRIPTION_CREATED', 'SUBSCRIPTION_CANCELLED', 'API_KEY_CREATED', 'DATA_EXPORT', name='auditeventtype'), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('borrower_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferred_languages', sa.JSON(), nullable=True),
    sa.Column('preferred_counties', sa.JSON(), nullable=True),
    sa.Column('loan_purpose', sa.String(length=50), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('estimated_credit_score', sa.String(length=20), nullable=True),
    sa.Column('contact_preference', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dispute_type', sa.Enum('BILLING', 'SERVICE', 'TECHNICAL', 'OTHER', name='disputetype'), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='disputestatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='disputepriority'), nullable=False),
    sa.Column('related_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_assigned_to'), 'disputes', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_index(op.f('ix_disputes_user_id'), 'disputes', ['user_id'], unique=False)
    op.create_table('professional_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('nmls_id', sa.String(length=20), nullable=True),
    sa.Column('nmls_verified', sa.Boolean(), nullable=False),
    sa.Column('nmls_verified_at', sa.DateTime(), nullable=True),
    sa.Column('office_address', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('prerecorded_video_url', sa.String(length=500), nullable=True),
    sa.Column('webcam_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('OFFLINE', 'ONLINE_AVAILABLE', 'ONLINE_BUSY', 'IN_CALL', 'AWAY', name='professionalstatus'), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('current_bid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('daily_bid_budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'BASIC', 'PROFESSIONAL', 'PREMIUM', name='subscriptiontier'), nullable=False),
    sa.Column('time_online_today_seconds', sa.Integer(), nullable=False),
    sa.Column('total_calls_completed', sa.Integer(), nullable=False),
    sa.Column('avg_pickup_time_seconds', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('profile_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_professional_profiles_nmls_id'), 'professional_profiles', ['nmls_id'], unique=False)
    op.create_table('bid_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('available_credits', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reserved_credits', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_deposited', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professional_id')
    )
    op.create_table('billing_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispute_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_messages_dispute_id'), 'dispute_messages', ['dispute_id'], unique=False)
    op.create_table('grid_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('click_type', sa.String(length=30), nullable=False),
    sa.Column('grid_position', sa.Integer(), nullable=True),
    sa.Column('filter_context', sa.JSON(), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grid_clicks_click_type', 'grid_clicks', ['click_type'], unique=False)
    op.create_index('ix_grid_clicks_pro_created', 'grid_clicks', ['professional_id', 'created_at'], unique=False)
    op.create_table('grid_impressions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions_count', sa.Integer(), nullable=False),
    sa.Column('clicks_count', sa.Integer(), nullable=False),
    sa.Column('calls_initiated', sa.Integer(), nullable=False),
    sa.Column('avg_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grid_impressions_date', 'grid_impressions', ['date'], unique=False)
    op.create_index('ix_grid_impressions_pro_date', 'grid_impressions', ['professional_id', 'date'], unique=True)
    op.create_table('partnerships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_officer_id', sa.UUID(), nullable=False),
    sa.Column('realtor_id', sa.UUID(), nullable=True),
    sa.Column('external_realtor_name', sa.String(length=100), nullable=True),
    sa.Column('external_realtor_email', sa.String(length=255), nullable=True),
    sa.Column('external_realtor_phone', sa.String(length=20), nullable=True),
    sa.Column('external_realtor_company', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'PAUSED', 'TERMINATED', name='partnershipstatus'), nullable=False),
    sa.Column('tier', sa.Enum('BASIC', 'SILVER', 'GOLD', 'PLATINUM', name='partnershiptier'), nullable=False),
    sa.Column('revenue_share_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('invitation_token', sa.String(length=64), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('widget_enabled', sa.Boolean(), nullable=False),
    sa.Column('widget_token', sa.String(length=64), nullable=True),
    sa.Column('widget_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_officer_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['realtor_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitation_token'),
    sa.UniqueConstraint('widget_token')
    )
    op.create_index(op.f('ix_partnerships_loan_officer_id'), 'partnerships', ['loan_officer_id'], unique=False)
    op.create_table('placement_bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('daily_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bid_per_impression', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('bid_per_click', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('target_counties', sa.JSON(), nullable=True),
    sa.Column('target_languages', sa.JSON(), nullable=True),
    sa.Column('target_specialties', sa.JSON(), nullable=True),
    sa.Column('target_hours', sa.JSON(), nullable=True),
    sa.Column('daily_spent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_languages',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('proficiency', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professional_id', 'language_id')
    )
    op.create_table('professional_service_areas',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professional_id', 'county_id')
    )
    op.create_table('professional_specialties',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professional_id', 'specialty_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'BASIC', 'PROFESSIONAL', 'PREMIUM', name='subscriptiontier'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'PAST_DUE', 'CANCELLED', 'TRIALING', name='subscriptionstatus'), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_expiry_month', sa.Integer(), nullable=True),
    sa.Column('card_expiry_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.String(length=100), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=True),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('initiated_at', sa.DateTime(), nullable=False),
    sa.Column('ring_started_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('pickup_time_seconds', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('INITIATED', 'RINGING', 'CONNECTED', 'COMPLETED', 'MISSED', 'DECLINED', 'FAILED', name='callstatus'), nullable=False),
    sa.Column('end_reason', sa.String(length=50), nullable=True),
    sa.Column('borrower_camera_on', sa.Boolean(), nullable=False),
    sa.Column('professional_camera_on', sa.Boolean(), nullable=False),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('ice_servers_used', sa.JSON(), nullable=True),
    sa.Column('quality_metrics', sa.JSON(), nullable=True),
    sa.Column('anonymous_session_id', sa.String(length=64), nullable=True),
    sa.Column('anonymous_device_fingerprint', sa.String(length=256), nullable=True),
    sa.Column('captured_name', sa.String(length=100), nullable=True),
    sa.Column('captured_email', sa.String(length=255), nullable=True),
    sa.Column('captured_phone', sa.String(length=20), nullable=True),
    sa.Column('lead_captured_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.create_index(op.f('ix_video_calls_anonymous_session_id'), 'video_calls', ['anonymous_session_id'], unique=False)
    op.create_table('video_moderations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='moderationstatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_moderations_professional_id'), 'video_moderations', ['professional_id'], unique=False)
    op.create_index(op.f('ix_video_moderations_status'), 'video_moderations', ['status'], unique=False)
    op.create_table('bid_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('related_call_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['bid_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=True),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('source_call_id', sa.UUID(), nullable=True),
    sa.Column('lead_status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'PROPOSAL_SENT', 'NEGOTIATION', 'WON', 'LOST', 'NURTURING', name='leadstatus'), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('loan_purpose', sa.String(length=50), nullable=True),
    sa.Column('property_address', sa.Text(), nullable=True),
    sa.Column('estimated_property_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_loan_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('next_followup_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['source_call_id'], ['video_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_call_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_professional_id', sa.UUID(), nullable=False),
    sa.Column('overall_rating', sa.SmallInteger(), nullable=False),
    sa.Column('knowledge_rating', sa.SmallInteger(), nullable=True),
    sa.Column('communication_rating', sa.SmallInteger(), nullable=True),
    sa.Column('responsiveness_rating', sa.SmallInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_verified_call', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('moderation_status', sa.String(length=20), nullable=False),
    sa.Column('professional_response', sa.Text(), nullable=True),
    sa.Column('professional_responded_at', sa.DateTime(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('communication_rating IS NULL OR (communication_rating >= 1 AND communication_rating <= 5)', name='check_communication_rating'),
    sa.CheckConstraint('knowledge_rating IS NULL OR (knowledge_rating >= 1 AND knowledge_rating <= 5)', name='check_knowledge_rating'),
    sa.CheckConstraint('overall_rating >= 1 AND overall_rating <= 5', name='check_overall_rating'),
    sa.CheckConstraint('responsiveness_rating IS NULL OR (responsiveness_rating >= 1 AND responsiveness_rating <= 5)', name='check_responsiveness_rating'),
    sa.ForeignKeyConstraint(['reviewed_professional_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_call_id'], ['video_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='scheduledcallstatus'), nullable=False),
    sa.Column('loan_purpose', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('completed_call_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_call_id'], ['video_calls.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_calls_scheduled_for'), 'scheduled_calls', ['scheduled_for'], unique=False)
    op.create_table('lead_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_metadata', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partnership_referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partnership_id', sa.UUID(), nullable=False),
    sa.Column('borrower_name', sa.String(length=100), nullable=False),
    sa.Column('borrower_email', sa.String(length=255), nullable=False),
    sa.Column('borrower_phone', sa.String(length=20), nullable=True),
    sa.Column('property_address', sa.String(length=500), nullable=True),
    sa.Column('loan_purpose', sa.String(length=50), nullable=True),
    sa.Column('estimated_amount', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('converted_to_lead_id', sa.UUID(), nullable=True),
    sa.Column('converted_to_call_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['converted_to_call_id'], ['video_calls.id'], ),
    sa.ForeignKeyConstraint(['converted_to_lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['partnership_id'], ['partnerships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partnership_referrals_partnership_id'), 'partnership_referrals', ['partnership_id'], unique=False)
    op.create_table('soft_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('loan_purpose', sa.String(length=50), nullable=True),
    sa.Column('estimated_amount', sa.Integer(), nullable=True),
    sa.Column('property_state', sa.String(length=2), nullable=True),
    sa.Column('property_county', sa.String(length=100), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('timeframe', sa.String(length=50), nullable=True),
    sa.Column('preferred_professional_type', sa.String(length=50), nullable=True),
    sa.Column('preferred_specialty', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'MATCHED', 'CONTACTED', 'CONVERTED', 'EXPIRED', name='softleadstatus'), nullable=False),
    sa.Column('matched_professional_id', sa.UUID(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('converted_lead_id', sa.UUID(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('referrer_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['converted_lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['matched_professional_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soft_leads_created_at'), 'soft_leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_soft_leads_email'), 'soft_leads', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soft_leads_email'), table_name='soft_leads')
    op.drop_index(op.f('ix_soft_leads_created_at'), table_name='soft_leads')
    op.drop_table('soft_leads')
    op.drop_index(op.f('ix_partnership_referrals_partnership_id'), table_name='partnership_referrals')
    op.drop_table('partnership_referrals')
    op.drop_table('lead_activities')
    op.drop_index(op.f('ix_scheduled_calls_scheduled_for'), table_name='scheduled_calls')
    op.drop_table('scheduled_calls')
    op.drop_table('reviews')
    op.drop_table('leads')
    op.drop_table('bid_transactions')
    op.drop_index(op.f('ix_video_moderations_status'), table_name='video_moderations')
    op.drop_index(op.f('ix_video_moderations_professional_id'), table_name='video_moderations')
    op.drop_table('video_moderations')
    op.drop_index(op.f('ix_video_calls_anonymous_session_id'), table_name='video_calls')
    op.drop_table('video_calls')
    op.drop_table('subscriptions')
    op.drop_table('professional_specialties')
    op.drop_table('professional_service_areas')
    op.drop_table('professional_languages')
    op.drop_table('placement_bids')
    op.drop_index(op.f('ix_partnerships_loan_officer_id'), table_name='partnerships')
    op.drop_table('partnerships')
    op.drop_index('ix_grid_impressions_pro_date', table_name='grid_impressions')
    op.drop_index('ix_grid_impressions_date', table_name='grid_impressions')
    op.drop_table('grid_impressions')
    op.drop_index('ix_grid_clicks_pro_created', table_name='grid_clicks')
    op.drop_index('ix_grid_clicks_click_type', table_name='grid_clicks')
    op.drop_table('grid_clicks')
    op.drop_index(op.f('ix_dispute_messages_dispute_id'), table_name='dispute_messages')
    op.drop_table('dispute_messages')
    op.drop_table('billing_transactions')
    op.drop_table('bid_wallets')
    op.drop_index(op.f('ix_professional_profiles_nmls_id'), table_name='professional_profiles')
    op.drop_table('professional_profiles')
    op.drop_index(op.f('ix_disputes_user_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_assigned_to'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_table('borrower_profiles')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('subscription_plans')
    op.drop_table('specialties')
    op.drop_table('languages')
    op.drop_table('counties')
    # ### end Alembic commands ###
